# Generated by Django 3.2.19 on 2023-10-13 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
